Repository magnetis/astro-native, pull requests merged in 2020-12, with the labels that each got.

#11 Implement ControlInput
  src/components/Inputs/ControlInput.tsx
  src/components/Inputs/TextInput.tsx
  src/components/Inputs/__tests__/ControlInput.test.tsx
  src/components/Inputs/__tests__/utils.test.ts
  src/components/Inputs/index.ts
  src/components/Inputs/utils.ts
  src/stories/Inputs.stories.tsx
Labels: enhancement

#12 Write Input docs
  .travis.yml
  src/components/Inputs/ControlInput.tsx
  src/components/Inputs/MaskedInput.tsx
  src/components/Inputs/TextInput.tsx
  src/components/Inputs/types.ts
Labels: documentation

#13 Write Buttons docs
  src/components/Buttons/BaseButton.tsx
  src/components/Buttons/BaseButtonText.tsx
  src/components/Buttons/GhostIconButton.tsx
  src/components/Buttons/GhostIconLabelButton.tsx
  src/components/Buttons/IconButton.tsx
  src/components/Buttons/IconLabelButton.tsx
  src/components/Buttons/IconLinkButton.tsx
  src/components/Buttons/Link.tsx
  src/components/Buttons/OutlineButton.tsx
  src/components/Buttons/OutlineIconButton.tsx
  src/components/Buttons/OutlineIconLabelButton.tsx
  src/components/Buttons/PrimaryButton.tsx
  src/components/Buttons/__tests__/BaseButton.test.tsx
  src/components/Buttons/__tests__/GhostIconButton.test.tsx
  src/components/Buttons/__tests__/GhostIconLabelButton.test.tsx
  src/components/Buttons/__tests__/IconButton.test.tsx
  src/components/Buttons/__tests__/IconLabelButton.test.tsx
  src/components/Buttons/__tests__/IconLinkButton.test.tsx
  src/components/Buttons/__tests__/OutlineButton.test.tsx
  src/components/Buttons/__tests__/OutlineIconButton.test.tsx
  src/components/Buttons/__tests__/OutlineIconLabelButton.test.tsx
  src/components/Buttons/__tests__/PrimaryButton.test.tsx
  src/components/Buttons/types.ts
  src/components/Buttons/utils.ts
  src/stories/Buttons.stories.tsx
Labels: documentation

#16 chore(ci): Make travisci deploy occur on tags only
  .travis.yml
Labels: bug

#17 fix(Inputs): change testID prop forward
  src/components/Inputs/ControlInput.tsx
  src/components/Inputs/MaskedInput.tsx
  src/components/Inputs/TextInput.tsx
Labels: fix

#18 Chore: fix changelog generator
  CHANGELOG.md
  package.json
  yarn.lock
Labels: enhancement

#22 chore(ci): Improve CI script
  .travis.yml
Labels: Chore

#24 release: bump version to v1.0.1
  CHANGELOG.md
  package.json
Labels: release

#28 Change tsconfig module to ES2015
  tsconfig.json
Labels: bug

#33 chore(package): Fix npm scripts
  package.json
  yarn.lock
Labels: chore

#35 release: bump version to v1.0.3
  CHANGELOG.md
  package.json
Labels: release

#36 chore: implement changes from develop that were lost
  src/components/Buttons/BaseButton.tsx
  src/components/Buttons/BaseButtonText.tsx
  src/components/Buttons/GhostIconButton.tsx
  src/components/Buttons/GhostIconLabelButton.tsx
  src/components/Buttons/IconButton.tsx
  src/components/Buttons/IconLabelButton.tsx
  src/components/Buttons/IconLinkButton.tsx
  src/components/Buttons/Link.tsx
  src/components/Buttons/OutlineButton.tsx
  src/components/Buttons/OutlineIconButton.tsx
  src/components/Buttons/OutlineIconLabelButton.tsx
  src/components/Buttons/PrimaryButton.tsx
  src/components/Buttons/__tests__/BaseButton.test.tsx
  src/components/Buttons/__tests__/GhostIconButton.test.tsx
  src/components/Buttons/__tests__/GhostIconLabelButton.test.tsx
  src/components/Buttons/__tests__/IconButton.test.tsx
  src/components/Buttons/__tests__/IconLabelButton.test.tsx
  src/components/Buttons/__tests__/OutlineButton.test.tsx
  src/components/Buttons/__tests__/OutlineIconButton.test.tsx
  src/components/Buttons/__tests__/OutlineIconLabelButton.test.tsx
  src/components/Buttons/__tests__/PrimaryButton.test.tsx
  src/components/Buttons/__tests__/utils.test.tsx
  src/components/Buttons/types.ts
  src/components/Buttons/utils.ts
  src/components/ControlsToggles/Checkbox.tsx
  src/components/ControlsToggles/Radio.tsx
  src/components/ControlsToggles/RadioGroup.tsx
  src/components/ControlsToggles/Slider.tsx
  src/components/ControlsToggles/Tabs.tsx
  src/components/ControlsToggles/Toggle.tsx
  src/components/ControlsToggles/__tests__/Toggle.test.tsx
  src/components/ControlsToggles/types.ts
  src/components/Icons/types.ts
  src/components/Inputs/ControlInput.tsx
  src/components/Inputs/MaskedInput.tsx
  src/components/Inputs/TextInput.tsx
  src/components/Inputs/types.ts
  src/components/Inputs/utils.ts
  src/components/Text/utils.ts
Labels: chore

#38 release: bump version to v1.1.0
  CHANGELOG.md
  package.json
Labels: release

#39 chore(ci): Fix deploy stage
  .travis.yml
Labels: chore

#40 feat(CurrencyInput): Implement controlled input support
  src/components/Inputs/CurrencyInput.tsx
  src/components/Inputs/__tests__/CurrencyInput.test.tsx
Labels: enhancement

#41 release: bump version to v1.2.0
  CHANGELOG.md
  package.json
Labels: release

#43 feat(Title): Implement Title component
  src/components/Text/Title.tsx
  src/components/Text/__tests__/Title.test.tsx
  src/components/Text/index.ts
  src/components/Text/stories/Title.story.tsx
  src/components/Text/stories/index.ts
Labels: enhancement

#45 release: bump version to v1.3.0
  CHANGELOG.md
  package.json
Labels: release

#46 ci: add before_deploy script
  .travis.yml
Labels: chore

#47 fix(TextInput): update state when value changes
  src/components/Inputs/InputLabel.tsx
  src/components/Inputs/TextInput.tsx
  src/components/Inputs/__tests__/TextInput.test.tsx
Labels: bug

#48 release: bump version to v1.3.1
  CHANGELOG.md
  package.json
Labels: release
