Repository magnetis/astro-native, pull requests merged in 2021-02, with the labels that each got.

#51 Chore/fix clean script
  package.json
Labels: chore

#54 [AST-7 | PRIM-666] fix(basebutton): min hitslop seted when button is smaller then 48
  src/components/Buttons/BaseButton.tsx
  src/components/Buttons/__tests__/BaseButton.test.tsx
Labels: bug

#55 Update contributing guide
  .github/CONTRIBUTING.md
Labels: documentation

#53 [AST-12] Fix text input error layout
  src/components/Inputs/InputErrorMessage.tsx
  src/components/Inputs/InputEyeToggle.tsx
  src/components/Inputs/TextInput.tsx
  src/components/Inputs/__tests__/InputErrorMessage.test.tsx
  src/components/Inputs/__tests__/TextInput.test.tsx
Labels: bug

#58 release: bump version to v1.4.0
  CHANGELOG.md
  package.json
Labels: release

#56 [AST-20] Fix Tab when has single item
  src/components/ControlsToggles/Tabs.tsx
  src/components/ControlsToggles/__tests__/Tabs.test.tsx
Labels: bug

#60 [AST-53] Fix currency input layout
  src/components/Inputs/MaskedInput.tsx
  src/components/Inputs/__tests__/MaskedInput.test.tsx
Labels: bug

#64 Add `release` type to commit lint config
  commitlint.config.js
Labels: chore

#65 release: bump version to v1.5.0
  CHANGELOG.md
  package.json
Labels: release
