Repository magnetis/astro-native, pull requests merged in 2021-03, with the labels that each got.

#67 [AST-55] Update secure api_token for deploy script
  .travis.yml
Labels: chore

#68 [AST-61] Fix secure text entry to be true when input is password
  src/components/Inputs/TextInput.tsx
  src/components/Inputs/__tests__/TextInput.test.tsx
Labels: bug

#69 [AST-63] release: bump version to v1.6.0
  CHANGELOG.md
  package.json
Labels: release

#72 release: bump version to v1.7.0
  CHANGELOG.md
  package.json
Labels: release
