Repository magnetis/astro-native, pull requests merged in 2021-11, with the labels that each got.

#349 Remove old Magnetis developers from reviewers
  .github/dependabot.yml
Labels: chore

#350 feat(tabs): add rounded prop
  src/components/Tabs/Tab.tsx
  src/components/Tabs/TabsContainer.tsx
  src/components/Tabs/index.ts
  src/components/Tabs/stories/TabsContainer.story.tsx
  src/index.ts
Labels: enhancement

#364 feat(icons): add icons
  src/components/Icons/Support/QuestionMark.tsx
  src/components/Icons/Support/Star.tsx
  src/components/Icons/Support/StarFilled.tsx
  src/components/Icons/Support/index.ts
Labels: enhancement

#366 release: bump version from 1.8.7 to 1.8.8
  CHANGELOG.md
  package.json
Labels: release
