Repository magnetis/astro-native, pull requests merged in 2022-07, with the labels that each got.

#612 Iconography: Improve IconID Type
  src/components/Buttons/__tests__/Button.test.tsx
  src/components/Buttons/__tests__/IconButton.test.tsx
  src/components/Icons/types.ts
Labels: chore

#613 chore(release): bump version from v2.0.0-next.7 to v2.0.0-next.8
  CHANGELOG.md
Labels: release

#615 Fix release script
  .github/workflows/publish.yml
Labels: bug

#616 chore: bump version from v2.0.0-next.6 to v2.0.0-next.7
  CHANGELOG.md
  package.json
Labels: release
