Repository magnetis/astro-native, pull requests merged in 2022-02, with the labels that each got.

#460 refactor(buttonsgroup): add containerJustifyContent and initialActive…
  src/components/ButtonsGroup/ButtonsGroup.tsx
  src/components/ButtonsGroup/__tests__/ButtonsGroup.test.tsx
  src/components/ButtonsGroup/stories/ButtonsGroup.story.tsx
Labels: enhancement

#461 chore: bump version to v2.0.0-next.4
  CHANGELOG.md
  package.json
Labels: release

#467 Update dependabot.yml
  .github/dependabot.yml
Labels: chore

#474 [AST-164] Fix legacy variant layout for outline and ghost button types
  src/components/Buttons/Button.tsx
  src/components/Buttons/__tests__/utils.test.tsx
  src/components/Buttons/utils.ts
Labels: enhancement

#475 chore: update shelljs to version 0.8.5
  yarn.lock
Labels: dependencies, security
