Repository magnetis/astro-native, pull requests merged in 2022-04, with the labels that each got.

#515 [AST-177] Enable husky and pre-commit hook
  package.json
Labels: enhancement, chore

#510 [AST-175] Update refractor to fix prismjs vulnerabilities
  package.json
  yarn.lock
Labels: security

#514 Add Button pressed feedback
  src/components/Buttons/BaseButton.tsx
  src/components/Buttons/__tests__/BaseButton.test.tsx
  src/components/Buttons/__tests__/Button.test.tsx
  src/components/Buttons/stories/Button.story.tsx
  src/components/Buttons/types.ts
Labels: enhancement

#533 chore: bump version from v1.8.9 to v1.9.0
  CHANGELOG.md
  package.json
Labels: release

#534 chore: bump version to v2.0.0-next.5 to v2.0.0-next.6
  CHANGELOG.md
  package.json
Labels: release
