Repository magnetis/astro-native, pull requests merged in 2023-06, with the labels that each got.

#718 chore(sideway/formula) update package sideway/formula from 3.0.0 to 3.0.1 in astro-native next [CONFIA-1201]
  yarn.lock
Labels: chore

#719 feat(link): allow use any color
  src/components/Buttons/Link.tsx
  src/components/Buttons/__tests__/Link.test.tsx
  src/components/Buttons/stories/Link.story.tsx
  src/components/Buttons/utils.ts
Labels: enhancement

#720 chore(react-native): update react native from 0.64.4 to 0.67.5 [CONFIA-1204]
  .bundle/config
  .editorconfig
  .gitattributes
  .gitignore
  .ruby-version
  Gemfile
  android/app/build.gradle
  android/app/src/main/res/drawable/rn_edit_text_material.xml
  android/app/src/main/res/values/styles.xml
  android/build.gradle
  android/gradle.properties
  android/gradle/wrapper/gradle-wrapper.properties
  ios/AstroNative.xcodeproj/project.pbxproj
  ios/Podfile
  ios/Podfile.lock
  package.json
  yarn.lock
Labels: chore

#721 chore(react-native): update react native to 0.67.5 [CONFIA-1214] of astro-native-next
  .bundle/config
  .editorconfig
  .gitattributes
  .gitignore
  .ruby-version
  Gemfile
  android/app/build.gradle
  android/app/src/main/res/drawable/rn_edit_text_material.xml
  android/app/src/main/res/values/styles.xml
  android/build.gradle
  android/gradle.properties
  android/gradle/wrapper/gradle-wrapper.properties
  ios/AstroNative.xcodeproj/project.pbxproj
  ios/Podfile
  ios/Podfile.lock
  package.json
  yarn.lock
Labels: chore

#723 chore: prepare for release v1.11.0
  ios/AstroNative.xcodeproj/project.pbxproj
  ios/Podfile.lock
  package.json
  src/components/Text/BaseText.tsx
  src/components/Text/PrimaryText.tsx
  yarn.lock
Labels: chore

#724 Release v1.11.0
  CHANGELOG.md
  package.json
Labels: release
