Repository magnetis/astro-native, pull requests merged in 2023-02, with the labels that each got.

#685 Fix Svg path in icon components [CONFIA-811]
  src/components/Icons/Arrows/ArrowRightDown.tsx
  src/components/Icons/Arrows/ArrowRightUp.tsx
Labels: chore

#687 feat(ButtounsGroup): update ButtonsGroup component [CONFIA-816]
  ios/Podfile.lock
  jest.config.js
  package.json
  src/components/ButtonsGroup/ButtonsGroup.tsx
  yarn.lock
Labels: enhancement

#691 fix(fonts): make fontWeight and fontStyle style props work for fonts
  android/app/src/main/java/com/astronative/MainApplication.java
  android/app/src/main/res/font/lato.xml
  android/app/src/main/res/font/lato_bold.ttf
  android/app/src/main/res/font/lato_regular.ttf
  android/app/src/main/res/font/poppins.xml
  android/app/src/main/res/font/poppins_black.ttf
  android/app/src/main/res/font/poppins_bold.ttf
  android/app/src/main/res/font/poppins_medium.ttf
  android/app/src/main/res/font/poppins_regular.ttf
  android/app/src/main/res/font/poppins_semibold.ttf
Labels: bug

#692 chore: upgrade react native to v0.65.3 for Astro Native Next [CONFIA-830]
  android/app/build.gradle
  android/build.gradle
  android/gradle.properties
  android/gradle/wrapper/gradle-wrapper.properties
  ios/AstroNative.xcodeproj/project.pbxproj
  ios/Podfile
  ios/Podfile.lock
  package.json
  yarn.lock
Labels: dependencies

#693 release: bump version from v2.0.0-next.8 to v2.0.0-next.9
  CHANGELOG.md
  package.json
Labels: release
