Repository magnetis/astro-native, pull requests merged in 2023-07, with the labels that each got.

#739 chore: upgrade lib jsdom from 16.4.0 to 16.7.0 in astro-native next
  yarn.lock
Labels: chore

#747 chore(commitizen): update commitizen library to 4.3.0 in astro-native [CONFIA-1278]
  package.json
  yarn.lock
Labels: dependencies

#749 chore(commitizen): update commitizen library to 4.3.0 in astro-native-next [CONFIA-1279]
  package.json
  yarn.lock
Labels: dependencies

#764 chore(deps): bump @magnetis/astro-tokens from 0.0.8 to 0.0.10
  package.json
  src/components/Buttons/__tests__/BaseButton.test.tsx
  src/components/Buttons/__tests__/Button.test.tsx
  src/components/Buttons/__tests__/IconButton.test.tsx
  src/components/Buttons/__tests__/utils.test.tsx
  src/components/Buttons/utils.ts
  src/components/Tabs/__tests__/TabsContainer.test.tsx
  src/components/Tabs/stories/TabsContainer.story.tsx
  yarn.lock
Labels: enhancement, dependencies

#765 chore: bump version to v2.0.0-next.11
  CHANGELOG.md
  package.json
Labels: release
