Repository magnetis/astro-native, pull requests merged in 2023-08, with the labels that each got.

#776 chore: bump node version from 14 to 16
  .github/workflows/publish.yml
  .github/workflows/pull-requests.yml
Labels: chore

#777 chore: bump node version from 14 to 16
  .github/workflows/publish.yml
  .github/workflows/pull-requests.yml
Labels: chore

#779 chore(dev-deps): bump codecov version from 3.8.1 to 3.8.3
  package.json
  yarn.lock
Labels: chore

#782 feat(components): add divider component in astro-native-next [CONFIA-1337]
  jest.config.js
  src/components/Divider/Divider.tsx
  src/components/Divider/__tests__/Divider.test.tsx
  src/components/Divider/constants.ts
  src/components/Divider/index.ts
  src/components/Divider/stories/Divider.story.tsx
  src/components/Divider/stories/index.ts
  src/components/Divider/types.ts
  src/index.ts
  storybook/stories.ts
Labels: enhancement

#791 feat(components): create tag component on astro-native@next [CONFIA-1335]
  jest.config.js
  src/components/Tags/Tag.tsx
  src/components/Tags/__tests___/Tag.test.tsx
  src/components/Tags/__tests___/utils.test.tsx
  src/components/Tags/constants.ts
  src/components/Tags/index.ts
  src/components/Tags/stories/Tag.story.tsx
  src/components/Tags/stories/index.ts
  src/components/Tags/types.ts
  src/components/Tags/utils.ts
  src/index.ts
  storybook/stories.ts
Labels: enhancement

#794 chore: bump version to v2.0.0-next.12
  CHANGELOG.md
  package.json
Labels: release

#797 chore: bump astro-native to v1.11.1
  CHANGELOG.md
  package.json
Labels: release

#799 chore(astro-native-next): add request review slack automation [CONFIA-1350]
  .github/CODEOWNERS
  .github/mention-to-slack.yml
  .github/workflows/request-review.yml
Labels: enhancement, chore

#800 chore(astro-native-main): add request review slack automation [CONFIA-1350]
  .github/CODEOWNERS
  .github/mention-to-slack.yml
  .github/workflows/request-review.yml
Labels: enhancement, chore
